import { useEffect, useState, type FormEvent } from 'react';
import { Pencil, Plus, Save, Trash2, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../../auth/AuthContext';
import { apiUrl } from '../../lib/config';
import { EmptyState, ErrorState, LoadingState, PermissionState } from '../../components/ui/AsyncState';

type Room = { id: string; name: string; capacity: number; floor: string | null; isActive: boolean };
type Teacher = { id: string; fullName: string; phoneNumber: string; subject: string; defaultCenterFee: string; assistantName: string | null; assistantPhone: string | null; isActive: boolean };
type Mode = 'rooms' | 'teachers';
async function request<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(apiUrl(`/api/management${path}`), { ...options, credentials: 'include', headers: { 'Content-Type': 'application/json', ...options?.headers } }); if (!response.ok) throw new Error('REQUEST_FAILED'); return (await response.json() as { data: T }).data; }

export function ManagementPage({ mode }: { mode: Mode }) {
  const { t } = useTranslation(); const { hasRole } = useAuth(); const isAdmin = hasRole('ADMIN');
  const [rooms, setRooms] = useState<Room[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [deleting, setDeleting] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(''); try { if (mode === 'rooms') setRooms((await request<{ rooms: Room[] }>('/rooms')).rooms); else setTeachers((await request<{ teachers: Teacher[] }>('/teachers')).teachers); } catch { setError(t('management.loadError')); } finally { setLoading(false); } };
  useEffect(() => { void load(); setEditing(null); }, [mode]);
  async function remove(path: string, id: string) { if (!window.confirm(t('management.confirmDelete')) || deleting) return; setDeleting(id); setError(''); try { await request(path, { method: 'DELETE' }); setSuccess(t('management.deleteSuccess', 'تم الحذف بنجاح.')); await load(); } catch { setError(t('management.deleteError')); } finally { setDeleting(null); } }
  const items = mode === 'rooms' ? rooms : teachers;
  return <section className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-400">{t('management.sectionLabel')}</p><h2 className="mt-1 text-2xl font-bold text-white">{t(`management.${mode}.title`)}</h2></div>{isAdmin && <button type="button" onClick={() => setEditing('new')} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold"><Plus className="h-4 w-4" />{t('management.add')}</button>}</div>{!isAdmin && <PermissionState />}{error && <ErrorState message={error} onRetry={() => void load()} />}{success && <p role="status" className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-200">{success}</p>}{editing && isAdmin && <ManagementForm mode={mode} id={editing === 'new' ? null : editing} room={rooms.find((item) => item.id === editing)} teacher={teachers.find((item) => item.id === editing)} onDone={() => { setEditing(null); setSuccess(t('management.saveSuccess', 'تم الحفظ بنجاح.')); void load(); }} onCancel={() => setEditing(null)} />}{loading ? <LoadingState /> : items.length === 0 ? <EmptyState message={t(mode === 'rooms' ? 'management.emptyRooms' : 'management.emptyTeachers')} /> : mode === 'rooms' ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rooms.map((room) => <article key={room.id} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-white">{room.name}</h3><p className="mt-2 text-sm text-slate-400">{t('management.rooms.capacity')}: {room.capacity}</p><p className="text-sm text-slate-400">{room.floor || t('management.rooms.noFloor')}</p></div><Status active={room.isActive} /></div>{isAdmin && <Actions busy={deleting === room.id} onEdit={() => setEditing(room.id)} onDelete={() => void remove(`/rooms/${room.id}`, room.id)} />}</article>)}</div> : <div className="grid gap-4 lg:grid-cols-2">{teachers.map((teacher) => <article key={teacher.id} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-white">{teacher.fullName}</h3><p className="mt-1 text-sm text-emerald-400">{teacher.subject}</p><p className="mt-3 text-sm text-slate-400">{t('management.teachers.phone')}: {teacher.phoneNumber}</p><p className="text-sm text-slate-400">{t('management.teachers.fee')}: {teacher.defaultCenterFee} {t('currency')}</p>{teacher.assistantName && <p className="text-sm text-slate-400">{t('management.teachers.assistant')}: {teacher.assistantName}</p>}</div><Status active={teacher.isActive} /></div>{isAdmin && <Actions busy={deleting === teacher.id} onEdit={() => setEditing(teacher.id)} onDelete={() => void remove(`/teachers/${teacher.id}`, teacher.id)} />}</article>)}</div>}</section>;
}

function Status({ active }: { active: boolean }) { const { t } = useTranslation(); return <span className={`rounded-full px-2 py-1 text-xs font-bold ${active ? 'bg-emerald-500/10 text-emerald-300' : 'bg-slate-800 text-slate-400'}`}>{active ? t('status.active') : t('status.inactive')}</span>; }
function Actions({ busy, onEdit, onDelete }: { busy: boolean; onEdit: () => void; onDelete: () => void }) { const { t } = useTranslation(); return <div className="mt-5 flex gap-2 border-t border-slate-800 pt-4"><button type="button" disabled={busy} onClick={onEdit} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-bold text-slate-300 disabled:opacity-50"><Pencil className="h-3.5 w-3.5" />{t('management.edit')}</button><button type="button" disabled={busy} onClick={onDelete} className="inline-flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-bold text-red-300 disabled:opacity-50"><Trash2 className="h-3.5 w-3.5" />{busy ? t('ui.processing') : t('management.delete')}</button></div>; }

function ManagementForm({ mode, id, room, teacher, onDone, onCancel }: { mode: Mode; id: string | null; room?: Room; teacher?: Teacher; onDone: () => void; onCancel: () => void }) {
  const { t } = useTranslation(); const [values, setValues] = useState<Record<string, string | number>>(() => (mode === 'rooms' ? { name: room?.name || '', capacity: room?.capacity || 30, floor: room?.floor || '' } : { fullName: teacher?.fullName || '', phoneNumber: teacher?.phoneNumber || '', subject: teacher?.subject || '', defaultCenterFee: teacher?.defaultCenterFee || 0, assistantName: teacher?.assistantName || '', assistantPhone: teacher?.assistantPhone || '' }) as Record<string, string | number>); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const change = (key: string, value: string) => setValues((current) => ({ ...current, [key]: key === 'capacity' || key === 'defaultCenterFee' ? Number(value) : value }));
  async function submit(event: FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); setError(''); try { await request(`${mode === 'rooms' ? '/rooms' : '/teachers'}${id ? `/${id}` : ''}`, { method: id ? 'PATCH' : 'POST', body: JSON.stringify(values) }); onDone(); } catch { setError(t('management.saveError')); } finally { setSaving(false); } }
  const fields = mode === 'rooms' ? [['name', t('management.rooms.name')], ['capacity', t('management.rooms.capacity')], ['floor', t('management.rooms.floor')]] : [['fullName', t('management.teachers.name')], ['phoneNumber', t('management.teachers.phone')], ['subject', t('management.teachers.subject')], ['defaultCenterFee', t('management.teachers.fee')], ['assistantName', t('management.teachers.assistant')], ['assistantPhone', t('management.teachers.assistantPhone')]];
  return <form onSubmit={submit} className="rounded-xl border border-emerald-500/20 bg-slate-900 p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">{id ? t('management.edit') : t('management.add')}</h3><button type="button" onClick={onCancel} aria-label={t('actions.close')}><X className="h-5 w-5" /></button></div><div className="grid gap-4 sm:grid-cols-2">{fields.map(([key, label]) => <label key={key} className="text-sm font-semibold text-slate-300">{label}<input required={key !== 'floor' && key !== 'assistantName' && key !== 'assistantPhone'} type={key === 'capacity' || key === 'defaultCenterFee' ? 'number' : key.toLowerCase().includes('phone') ? 'tel' : 'text'} min={key === 'capacity' ? 1 : key === 'defaultCenterFee' ? 0 : undefined} step={key === 'defaultCenterFee' ? '0.01' : undefined} value={values[key]} onChange={(event) => change(key, event.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-3 text-white outline-none focus:border-emerald-500" /></label>)}</div>{error && <ErrorState message={error} />}<button disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold disabled:opacity-60"><Save className="h-4 w-4" />{saving ? t('management.saving') : t('management.save')}</button></form>;
}
