import { useEffect, useState, type FormEvent } from 'react';
import { Pencil, Plus, Save, Search, Trash2, X } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../../auth/AuthContext';
import { apiUrl } from '../../lib/config';
import { EmptyState, ErrorState, LoadingState } from '../../components/ui/AsyncState';

type Student = { id: string; studentCode: string; fullName: string; studentPhone: string | null; guardianPhone: string; academicStage: string; schoolType: string; notes: string | null };
type StudentForm = Omit<Student, 'id' | 'studentCode' | 'notes'> & { notes: string };
const emptyForm: StudentForm = { fullName: '', studentPhone: '', guardianPhone: '', academicStage: '', schoolType: 'GENERAL', notes: '' };
async function request<T>(path: string, options?: RequestInit): Promise<T> { const response = await fetch(apiUrl(`/api/registry${path}`), { ...options, credentials: 'include', headers: { 'Content-Type': 'application/json', ...options?.headers } }); if (!response.ok) throw new Error('REQUEST_FAILED'); return (await response.json() as { data: T }).data; }

export function StudentsPage() {
  const { t } = useTranslation(); const { hasRole } = useAuth(); const canEdit = hasRole('ADMIN', 'RECEPTIONIST'); const isAdmin = hasRole('ADMIN');
  const [students, setStudents] = useState<Student[]>([]); const [search, setSearch] = useState(''); const [form, setForm] = useState<StudentForm | null>(null); const [editingId, setEditingId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [deleting, setDeleting] = useState<string | null>(null);
  const load = async (value = search) => { setLoading(true); try { setStudents((await request<{ students: Student[] }>(`/students?search=${encodeURIComponent(value)}`)).students); setError(''); } catch { setError(t('students.loadError')); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 250); return () => window.clearTimeout(timer); }, [search]);
  const startEdit = (student: Student) => { setEditingId(student.id); setForm({ fullName: student.fullName, studentPhone: student.studentPhone || '', guardianPhone: student.guardianPhone, academicStage: student.academicStage, schoolType: student.schoolType, notes: student.notes || '' }); };
  async function remove(id: string) { if (!window.confirm(t('students.confirmDelete')) || deleting) return; setDeleting(id); try { await request(`/students/${id}`, { method: 'DELETE' }); await load(); } catch { setError(t('students.deleteError')); } finally { setDeleting(null); } }
  return <section className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-400">{t('students.sectionLabel')}</p><h2 className="mt-1 text-2xl font-bold text-white">{t('students.title')}</h2></div>{canEdit && <button type="button" onClick={() => { setEditingId(null); setForm(emptyForm); }} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold"><Plus className="h-4 w-4" />{t('students.quickAdd')}</button>}</div><div className="relative"><Search className="absolute start-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-500" aria-hidden="true" /><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t('students.search')} className="w-full rounded-xl border border-slate-800 bg-slate-900 py-3 ps-10 pe-3 text-white outline-none focus:border-emerald-500" /></div>{error && <ErrorState message={error} onRetry={() => void load()} />}{form && <StudentEditor form={form} id={editingId} onDone={() => { setForm(null); void load(); }} onChange={setForm} onCancel={() => setForm(null)} />}{loading ? <LoadingState /> : students.length === 0 ? <EmptyState message={t('students.empty')} /> : <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[700px] text-start text-sm"><thead className="bg-slate-900 text-slate-400"><tr>{['code', 'name', 'phone', 'stage', 'school'].map((key) => <th key={key} scope="col" className="px-4 py-3 text-start">{t(`students.table.${key}`)}</th>)}<th scope="col" className="px-4 py-3 text-start">{t('students.table.actions')}</th></tr></thead><tbody>{students.map((student) => <tr key={student.id} className="border-t border-slate-800 bg-slate-950"><td className="px-4 py-4 font-mono text-xs text-emerald-400">{student.studentCode}</td><td className="px-4 py-4 font-bold text-white">{student.fullName}</td><td className="px-4 py-4 text-slate-400">{student.studentPhone || student.guardianPhone}</td><td className="px-4 py-4 text-slate-400">{student.academicStage}</td><td className="px-4 py-4 text-slate-400">{t(`students.school.${student.schoolType.toLowerCase()}`)}</td><td className="px-4 py-4"><div className="flex gap-2">{canEdit && <button type="button" onClick={() => startEdit(student)} aria-label={t('students.edit')} className="rounded-lg p-2 text-slate-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-emerald-400"><Pencil className="h-4 w-4" /></button>}{isAdmin && <button type="button" disabled={deleting !== null} onClick={() => void remove(student.id)} aria-label={t('students.delete')} className="rounded-lg p-2 text-red-300 disabled:opacity-50"><Trash2 className="h-4 w-4" /></button>}</div></td></tr>)}</tbody></table></div>}</section>;
}

function StudentEditor({ form, id, onChange, onDone, onCancel }: { form: StudentForm; id: string | null; onChange: (form: StudentForm) => void; onDone: () => void; onCancel: () => void }) {
  const { t } = useTranslation(); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const set = (key: keyof StudentForm, value: string) => onChange({ ...form, [key]: value });
  async function submit(event: FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); setError(''); try { await request(`/students${id ? `/${id}` : ''}`, { method: id ? 'PATCH' : 'POST', body: JSON.stringify(form) }); onDone(); } catch { setError(t('students.saveError')); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="rounded-xl border border-emerald-500/20 bg-slate-900 p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">{id ? t('students.edit') : t('students.quickAdd')}</h3><button type="button" onClick={onCancel} aria-label={t('actions.close')}><X className="h-5 w-5" /></button></div><div className="grid gap-4 sm:grid-cols-2"><Field label={t('students.form.name')} value={form.fullName} onChange={(value) => set('fullName', value)} required /><Field label={t('students.form.studentPhone')} value={form.studentPhone || ''} onChange={(value) => set('studentPhone', value)} type="tel" /><Field label={t('students.form.guardianPhone')} value={form.guardianPhone} onChange={(value) => set('guardianPhone', value)} type="tel" required /><Field label={t('students.form.stage')} value={form.academicStage} onChange={(value) => set('academicStage', value)} required /><label className="text-sm font-semibold text-slate-300">{t('students.form.school')}<select value={form.schoolType} onChange={(event) => set('schoolType', event.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-3 text-white"><option value="GENERAL">{t('students.school.general')}</option><option value="LANGUAGES">{t('students.school.languages')}</option><option value="AZHAR">{t('students.school.azhar')}</option></select></label></div>{error && <ErrorState message={error} />}<div className="mt-5 flex flex-wrap gap-2"><button disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold disabled:opacity-60"><Save className="h-4 w-4" />{saving ? t('students.saving') : t('students.save')}</button><button type="button" onClick={onCancel} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">{t('actions.cancel')}</button></div></form>;
}
function Field({ label, value, onChange, required, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; required?: boolean; type?: string }) { return <label className="text-sm font-semibold text-slate-300">{label}<input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-3 text-white outline-none focus:border-emerald-500" /></label>; }
