import { useEffect, useState, type FormEvent } from 'react';
import { CalendarPlus, Clock3, MapPin, Save } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../../auth/AuthContext';
import { apiUrl } from '../../lib/config';

type Session = { id: string; title: string; academicStage: string; startTime: string; endTime: string; sessionPrice: string; centerFeePerStudent: string; status: string; teacher: { fullName: string; subject: string }; room: { name: string } };
type Option = { id: string; name?: string; fullName?: string; subject?: string };
const request = async <T,>(path: string, options?: RequestInit): Promise<T> => { const response = await fetch(apiUrl(`/api${path}`), { ...options, credentials: 'include', headers: { 'Content-Type': 'application/json', ...options?.headers } }); const body = await response.json() as { data: T; error?: { message?: string; messageEn?: string } }; if (!response.ok) throw new Error(body.error?.message || body.error?.messageEn || 'Request failed'); return body.data; };

export function SchedulingPage() {
  const { t } = useTranslation(); const { hasRole } = useAuth(); const [sessions, setSessions] = useState<Session[]>([]); const [teachers, setTeachers] = useState<Option[]>([]); const [rooms, setRooms] = useState<Option[]>([]); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const load = async () => { try { const [sessionData, teacherData, roomData] = await Promise.all([request<{ sessions: Session[] }>('/scheduling/sessions'), request<{ teachers: Option[] }>('/management/teachers'), request<{ rooms: Option[] }>('/management/rooms')]); setSessions(sessionData.sessions); setTeachers(teacherData.teachers); setRooms(roomData.rooms); } catch { setError(t('scheduling.loadError')); } };
  useEffect(() => { void load(); }, []);
  return <section className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-400">{t('scheduling.sectionLabel')}</p><h2 className="mt-1 text-2xl font-bold text-white">{t('scheduling.title')}</h2></div>{hasRole('ADMIN') && <button type="button" onClick={() => setShowForm((value) => !value)} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold hover:bg-emerald-500"><CalendarPlus className="h-4 w-4" />{t('scheduling.add')}</button>}</div>{error && <p role="alert" className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{showForm && <SessionForm teachers={teachers} rooms={rooms} onDone={() => { setShowForm(false); void load(); }} />}{sessions.length === 0 ? <div className="rounded-xl border border-dashed border-slate-700 p-10 text-center text-slate-400">{t('scheduling.empty')}</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sessions.map((session) => <article key={session.id} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-emerald-400">{session.teacher.subject}</p><h3 className="mt-1 font-bold text-white">{session.title}</h3><p className="text-sm text-slate-400">{session.teacher.fullName} · {session.academicStage}</p></div><span className="rounded-full bg-sky-500/10 px-2 py-1 text-xs font-bold text-sky-300">{t(`status.${session.status.toLowerCase()}`, session.status)}</span></div><div className="mt-5 space-y-2 border-t border-slate-800 pt-4 text-sm text-slate-300"><p className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-slate-500" />{new Date(session.startTime).toLocaleString()} - {new Date(session.endTime).toLocaleTimeString()}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-slate-500" />{session.room.name}</p><p className="font-semibold text-amber-300">{session.sessionPrice} {t('currency')} · {t('scheduling.centerFee')}: {session.centerFeePerStudent} {t('currency')}</p></div></article>)}</div>}</section>;
}

function SessionForm({ teachers, rooms, onDone }: { teachers: Option[]; rooms: Option[]; onDone: () => void }) {
  const { t } = useTranslation(); const [form, setForm] = useState({ teacherId: teachers[0]?.id || '', roomId: rooms[0]?.id || '', title: '', academicStage: '', startTime: '', endTime: '', sessionPrice: '100', centerFeePerStudent: '20' }); const [error, setError] = useState(''); const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); try { await request('/scheduling/sessions', { method: 'POST', body: JSON.stringify({ ...form, sessionPrice: Number(form.sessionPrice), centerFeePerStudent: Number(form.centerFeePerStudent), startTime: new Date(form.startTime).toISOString(), endTime: new Date(form.endTime).toISOString() }) }); onDone(); } catch (caught) { setError(caught instanceof Error ? caught.message : t('scheduling.saveError')); } }
  const fields = [['title', t('scheduling.form.title')], ['academicStage', t('scheduling.form.stage')], ['startTime', t('scheduling.form.start')], ['endTime', t('scheduling.form.end')], ['sessionPrice', t('scheduling.form.price')], ['centerFeePerStudent', t('scheduling.form.fee')]];
  return <form onSubmit={submit} className="rounded-xl border border-emerald-500/20 bg-slate-900 p-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-300">{t('scheduling.form.teacher')}<select value={form.teacherId} onChange={(event) => set('teacherId', event.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white">{teachers.map((item) => <option key={item.id} value={item.id}>{item.fullName}</option>)}</select></label><label className="text-sm font-semibold text-slate-300">{t('scheduling.form.room')}<select value={form.roomId} onChange={(event) => set('roomId', event.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white">{rooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{fields.map(([key, label]) => <label key={key} className="text-sm font-semibold text-slate-300">{label}<input required type={key.includes('Time') ? 'datetime-local' : key === 'sessionPrice' || key === 'centerFeePerStudent' ? 'number' : 'text'} min={key === 'sessionPrice' || key === 'centerFeePerStudent' ? 0 : undefined} step={key === 'sessionPrice' || key === 'centerFeePerStudent' ? '0.01' : undefined} value={form[key as keyof typeof form]} onChange={(event) => set(key, event.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white outline-none focus:border-emerald-500" /></label>)}</div>{error && <p className="mt-4 text-sm text-red-300">{error}</p>}<button className="mt-5 inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 text-sm font-bold hover:bg-emerald-500"><Save className="h-4 w-4" />{t('scheduling.save')}</button></form>;
}
